// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package main

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en": &dictionary{index: enIndex, data: enData},
		"ru": &dictionary{index: ruIndex, data: ruData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"%s=%.2f": 11,
	"/airQualityIndex - get the Air Quality Index for the location,\n/about      - into about the bot.": 5,
	"Air Quality Index":     1,
	"Details":               3,
	"Error! Please, retry!": 0,
	"Error: %v":             10,
	"Get the Air Quality Index (AQI) for the current location.\nContact: %s": 8,
	"Just share your location or try /start":                                 9,
	"Location: %f;%f. Last AQI: %s":                                          7,
	"Notify Me on AQI changes":                                               2,
	"OK. I won't notify you anymore":                                         12,
	"Share location!":                                                        4,
	"You have %d subscription(s)":                                            6,
	"😌 AQI gets better":                                                      14,
	"😷 AQI gets worse":                                                       13,
}

var enIndex = []uint32{ // 16 elements
	0x00000000, 0x00000016, 0x00000028, 0x00000041,
	0x00000049, 0x00000059, 0x000000ba, 0x000000d9,
	0x00000100, 0x00000149, 0x00000170, 0x0000017d,
	0x0000018b, 0x000001aa, 0x000001be, 0x000001d2,
} // Size: 88 bytes

const enData string = "" + // Size: 466 bytes
	"\x02Error! Please, retry!\x02Air Quality Index\x02Notify Me on AQI chang" +
	"es\x02Details\x02Share location!\x02/airQualityIndex - get the Air Quali" +
	"ty Index for the location,\x0a/about      - into about the bot.\x02You h" +
	"ave %[1]d subscription(s)\x02Location: %[1]f;%[2]f. Last AQI: %[3]s\x02G" +
	"et the Air Quality Index (AQI) for the current location.\x0aContact: %[1" +
	"]s\x02Just share your location or try /start\x02Error: %[1]v\x02%[1]s=%." +
	"2[2]f\x02OK. I won't notify you anymore\x02😷 AQI gets worse\x02😷 AQI get" +
	"s worse"

var ruIndex = []uint32{ // 16 elements
	0x00000000, 0x00000042, 0x00000075, 0x000000b1,
	0x000000be, 0x000000e4, 0x0000017f, 0x00000197,
	0x000001d8, 0x00000257, 0x000002b6, 0x000002ca,
	0x000002ca, 0x000002eb, 0x00000307, 0x00000323,
} // Size: 88 bytes

const ruData string = "" + // Size: 803 bytes
	"\x02Ошибка! Пожлуйста, повторите запрос\x02Индекс Качества Воздуха (AQI)" +
	"\x02Уведомлять меня об изменениях AQI\x02Детали\x02Оправить геопозицию" +
	"\x02/airQualityIndex - Индекс Качества Воздуха (AQI) для местоположения," +
	"\x0a/about      - информация о боте.\x02Подписок %[1]d.\x02Координаты: %" +
	"[1]f;%[2]f. Последний AQI: %[3]s\x02Индекс Качества Воздуха (AQI) для те" +
	"кущего местоположения.\x0aКонтакт: %[1]s\x02Поделитесь своим местополож" +
	"ением или начните с /start\x02Ошибка: %[1]v\x02Подписки удалены.\x02😷 A" +
	"QI ухудшился\x02😷 AQI ухудшился"

	// Total table size 1445 bytes (1KiB); checksum: 232B4B33
